P/Controllers/AdminDoctorController.cs
using System.Data.Entity;
using Hospital.IRepo;
using Hospital.Repo;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using P.Models;
using IHostingEnvironment = Microsoft.AspNetCore.Hosting.IHostingEnvironment;

namespace P.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdminDoctorController : Controller
    {
        private readonly HospitalContext context;
        private readonly IDoctor DoctorRepo;
        private readonly IHostingEnvironment hostingEnvironment;

        public AdminDoctorController(HospitalContext _context,IDoctor DoctorRepo,IHostingEnvironment hostingEnvironment)
        {
            context = _context;
            this.DoctorRepo = DoctorRepo;
            this.hostingEnvironment = hostingEnvironment;
        }


        public IActionResult DocView()
        {
            List<Doctor> doc = DoctorRepo.GetAll();

            return View(doc);
        }
        public IActionResult Add()
        {
            ViewData["deptlist"] = context.Departments.ToList();
            return View();
        }
        public IActionResult DocAdd(Doctor doc,IFormFile ImgNameFile)
        {   string fileName=string.Empty;
            if (ImgNameFile.FileName != null) {
                string path = Path.Combine(hostingEnvironment.WebRootPath,"uploads");
                fileName=ImgNameFile.FileName;
                string fullpath=Path.Combine(path,fileName);
                ImgNameFile.CopyTo(new FileStream(fullpath,FileMode.Create));
            }
            if (doc != null)
            {
                doc.ImgName = fileName;
                DoctorRepo.Insert(doc);
                return RedirectToAction("DocView");
            }

            ViewData["deptlist"] = context.Departments.ToList();
            return View("Add");
        }

        public IActionResult Edit(int id)
        {
            Doctor doc = DoctorRepo.GetByID(id);

            ViewData["deptlist"] = context.Departments.ToList();
            return View(doc);
        }
        public IActionResult DocEdit(int id, Doctor doc,IFormFile ImgNameFile)
        {
            string fileName = string.Empty;
            if (ImgNameFile.FileName != null)
            {
                string path = Path.Combine(hostingEnvironment.WebRootPath, "uploads");
                fileName = ImgNameFile.FileName;
                string fullpath = Path.Combine(path, fileName);
                ImgNameFile.CopyTo(new FileStream(fullpath, FileMode.Create));
            }

            Doctor oldoc = DoctorRepo.GetByID(id);
            if (oldoc != null)
            {
                doc.ImgName = fileName;
                DoctorRepo.Update(id,doc);
                context.SaveChanges();
                return RedirectToAction("DocView");
            }

            ViewData["deptlist"] = context.Departments.ToList();
            return View("Edit", doc);
        }
        public IActionResult Delete(int id)
        {
            DoctorRepo.Delete(id);
            return RedirectToAction("DocView");
        }
    }
}

P/Views/AdminDoctor/Add.cshtml
@model P.Models.Doctor

@{
    ViewData["Title"] = "Add";

    Layout = "/Views/Shared/_AdminBodyLayout.cshtml";
}

<h1>Add</h1>

<h4>Doctor</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="DocAdd" enctype="multipart/form-data">
            <div class="form-group">
                <label asp-for="F_Name" class="control-label"></label>
                <input asp-for="F_Name" class="form-control" />
                <span asp-validation-for="F_Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="M_Name" class="control-label"></label>
                <input asp-for="M_Name" class="form-control" />
                <span asp-validation-for="M_Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="L_Name" class="control-label"></label>
                <input asp-for="L_Name" class="form-control" />
                <span asp-validation-for="L_Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Street" class="control-label"></label>
                <input asp-for="Street" class="form-control" />
                <span asp-validation-for="Street" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Salary" class="control-label"></label>
                <input asp-for="Salary" class="form-control" />
                <span asp-validation-for="Salary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hire_Date" class="control-label"></label>
                <input asp-for="Hire_Date" class="form-control" />
                <span asp-validation-for="Hire_Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                <input asp-for="Gender" class="form-control" />
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Shift_Type" class="control-label"></label>
                <input asp-for="Shift_Type" class="form-control" />
                <span asp-validation-for="Shift_Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DeptId" class="control-label"></label>
                <select asp-for="DeptId" class ="form-control" >

                    @foreach(Department item in ViewBag.deptlist)
                    {
                        <option value="@item.DeptId">@item.DeptName</option>
                    }
                </select>
            </div>
            <div class="form-group">
                <label asp-for="ImgName" class="control-label"></label>
                <input type="file" name="ImgNameFile" asp-for="ImgName" class="form-control" />
                <span asp-validation-for="ImgName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Add" class="genric-btn primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

P/Views/AdminDoctor/DocView.cshtml
@model IEnumerable<P.Models.Doctor>

@{
    ViewData["Title"] = "DocView";

    Layout = "/Views/Shared/_AdminBodyLayout.cshtml";
}


<p>
    <a asp-action="Add" class="genric-btn info">Add New Doctor</a>
</p>
<div class="table-responsive">
<table class="table">
        <thead class="thead-dark">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.F_Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.M_Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.L_Name)
            </th>
            <th>
                image
            </th>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Street)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Salary)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Hire_Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Gender)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Shift_Type)
            </th>
            <th>
                Department Name
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.F_Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.M_Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.L_Name)
            </td>
            <td>
                        @if (item.ImgName != null)
                        {
                            <img src="~/uploads/@item.ImgName
                                " class="rounded mx-auto d-block" width="100px" height="100px" />
                        }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Street)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Salary)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Hire_Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gender)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Shift_Type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Dept.DeptName)
            </td>
            <td>
                    <a asp-action="Edit" asp-route-id="@item.DId" class="genric-btn link">Edit</a>
                    <a asp-action="Delete" asp-route-id="@item.DId" class="genric-btn link">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
</div>

P/Views/AdminDoctor/Edit.cshtml
@model P.Models.Doctor

@{
    ViewData["Title"] = "Edit";

    Layout = "/Views/Shared/_AdminBodyLayout.cshtml";
}

<h1>Edit</h1>

<h4>Doctor</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="DocEdit" asp-controller="AdminDoctor" asp-route-id="@Model.DId" enctype="multipart/form-data">
            <input type="hidden" asp-for="DId" />
            <div class="form-group">
                <label asp-for="F_Name" class="control-label"></label>
                <input asp-for="F_Name" class="form-control" />
                <span asp-validation-for="F_Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="M_Name" class="control-label"></label>
                <input asp-for="M_Name" class="form-control" />
                <span asp-validation-for="M_Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="L_Name" class="control-label"></label>
                <input asp-for="L_Name" class="form-control" />
                <span asp-validation-for="L_Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Street" class="control-label"></label>
                <input asp-for="Street" class="form-control" />
                <span asp-validation-for="Street" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Salary" class="control-label"></label>
                <input asp-for="Salary" class="form-control" />
                <span asp-validation-for="Salary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hire_Date" class="control-label"></label>
                <input asp-for="Hire_Date" class="form-control" />
                <span asp-validation-for="Hire_Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                <input asp-for="Gender" class="form-control" />
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Shift_Type" class="control-label"></label>
                <input asp-for="Shift_Type" class="form-control" />
                <span asp-validation-for="Shift_Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DeptId" class="control-label"></label>
                <select asp-for="DeptId" class="form-control" >
                    @foreach (Department item in ViewBag.deptlist)
                    {
                        <option value="@item.DeptId">@item.DeptName</option>
                    }
                </select>
                <span asp-validation-for="DeptId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImgName" class="control-label"></label>
                <input type="file" name="ImgNameFile" asp-for="ImgName" class="form-control" />
                <span asp-validation-for="ImgName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>